# name: Test Self-Hosted Runner
# on: [push]
# jobs:
#   test:
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v2
#     - name: Run a one-line script
#       run: echo Hello, world!

name: Test Self-Hosted Runner

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run a simple command
      run: echo "Hello from self-hosted runner!"
