name: Test Self-Hosted Runner
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run a test
      run: echo "Hello from self-hosted runner in Gitpod!"


# name: Actions Runner Controller Demo
# on:
#   workflow_dispatch:

# jobs:
#   Explore-GitHub-Actions:
#     # You need to use the INSTALLATION_NAME from the previous step
#     runs-on: actions-runner-controller
#     steps:
#     - run: echo "🎉 This job uses runner scale set runners!"
