name: Test Self-Hosted Runners

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run a one-liner script
      run: echo "This is running on a self-hosted runner!"


# name: Actions Runner Controller Demo
# on:
#   workflow_dispatch:

# jobs:
#   Explore-GitHub-Actions:
#     # You need to use the INSTALLATION_NAME from the previous step
#     runs-on: actions-runner-controller
#     steps:
#     - run: echo "🎉 This job uses runner scale set runners!"
